global using RabbitEvents.Application.Interfaces;
global using RabbitEvents.Application.Validators;
global using RabbitEvents.Domain.Entities;
global using RabbitEvents.Domain.Interfaces.Repositories;
global using RabbitEvents.ImagesConsumers.Helpers;
global using RabbitEvents.Shared.Configurations;
global using RabbitEvents.Shared.Constants;
global using RabbitEvents.Shared.Dtos;
global using System.Text.Json;
